/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color; // Import Color class
import java.awt.Image;
import java.awt.event.ActionEvent; // Import ActionEvent
import java.awt.event.ActionListener; // Import ActionListener
import java.awt.geom.RoundRectangle2D;
import javax.swing.ImageIcon;
import javax.swing.Timer; // Import javax.swing.Timer

/**
 *
 * @author DELL
 */
public class AttentionScreen extends javax.swing.JFrame {
    
    private Timer flickerTimer;

    public AttentionScreen() {
        initComponents();
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 30, 30));
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/edubridgeicon.png"));
            Image image = icon.getImage();
            this.setIconImage(image);
        } catch (Exception e) {
            System.err.println("Error loading icon: " + e.getMessage());
        }
        addEscapeListener();
        startFlickerEffect();
        MessageTextArea.setBackground(new java.awt.Color(0, 0, 0, 0));
        MessageTextArea.setCaret(null);
        MessageScrollPane.getViewport().setOpaque(false);
    }
    
    private void startFlickerEffect() {
        int delay = 500; 
        
        ActionListener taskPerformer = new ActionListener() {
            private boolean isRed = true;

            @Override
            public void actionPerformed(ActionEvent evt) {
                if (isRed) {
                    Attention.setForeground(Color.BLACK);
                } else {
                    Attention.setForeground(Color.RED);
                }
                isRed = !isRed;
            }
        };

        flickerTimer = new Timer(delay, taskPerformer);
        
        flickerTimer.start();
    }
    
    private void addEscapeListener() {
        // Define the action to be performed (disposing the frame)
        ActionListener escListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        };

        // Bind the ESCAPE key to the action in the RootPane
        this.getRootPane().registerKeyboardAction(escListener,
                javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0),
                javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainAttentionScreenPanel = new ui.GradientPanel();
        Header = new ui.GlassmorphismPanel();
        Welcome = new javax.swing.JLabel();
        CloseIcon = new javax.swing.JLabel();
        Main = new javax.swing.JPanel();
        Attention = new javax.swing.JLabel();
        MessagePanel = new ui.GlassmorphismPanel();
        MessageScrollPane = new javax.swing.JScrollPane();
        MessageTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);

        MainAttentionScreenPanel.setPreferredSize(new java.awt.Dimension(600, 500));

        Header.setOpaque(false);
        Header.setPreferredSize(new java.awt.Dimension(500, 94));

        Welcome.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        Welcome.setForeground(new java.awt.Color(151, 137, 219));
        Welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome.setText("Welecome to EduBridge!");

        CloseIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CloseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/icons8-close-24.png"))); // NOI18N
        CloseIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(262, 262, 262)
                .addComponent(CloseIcon)
                .addGap(20, 20, 20))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(CloseIcon))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        Main.setOpaque(false);

        Attention.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        Attention.setForeground(new java.awt.Color(255, 0, 0));
        Attention.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Attention.setText("Attention!!");

        MessagePanel.setOpaque(false);

        MessageScrollPane.setBorder(null);
        MessageScrollPane.setOpaque(false);

        MessageTextArea.setEditable(false);
        MessageTextArea.setText("Dear All Students/Employees,\n\nWe're excited to have you on board!\n\nPlease use the following credentials:\n\n👤 Username: Student ID (12345)\n🔑 Password: Student123\n\n👤 Username: Employee ID (F1234)\n🔑 Password:  Employee123\n\n📌 Important: Change your password after your first login for security.\n\nWishing you a great start! 🚀\n\nRegards!\nEduBridge");
        MessageTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MessageTextArea.setFocusable(false);
        MessageTextArea.setOpaque(false);
        MessageScrollPane.setViewportView(MessageTextArea);

        javax.swing.GroupLayout MessagePanelLayout = new javax.swing.GroupLayout(MessagePanel);
        MessagePanel.setLayout(MessagePanelLayout);
        MessagePanelLayout.setHorizontalGroup(
            MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
            .addGroup(MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MessagePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(MessageScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        MessagePanelLayout.setVerticalGroup(
            MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
            .addGroup(MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MessagePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(MessageScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Attention)
                .addGap(245, 245, 245))
            .addGroup(MainLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(MessagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Attention)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MessagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainAttentionScreenPanelLayout = new javax.swing.GroupLayout(MainAttentionScreenPanel);
        MainAttentionScreenPanel.setLayout(MainAttentionScreenPanelLayout);
        MainAttentionScreenPanelLayout.setHorizontalGroup(
            MainAttentionScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainAttentionScreenPanelLayout.createSequentialGroup()
                .addGroup(MainAttentionScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainAttentionScreenPanelLayout.createSequentialGroup()
                        .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(MainAttentionScreenPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MainAttentionScreenPanelLayout.setVerticalGroup(
            MainAttentionScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainAttentionScreenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainAttentionScreenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainAttentionScreenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseIconMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CloseIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttentionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttentionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttentionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttentionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttentionScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Attention;
    private javax.swing.JLabel CloseIcon;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel MainAttentionScreenPanel;
    private javax.swing.JPanel MessagePanel;
    private javax.swing.JScrollPane MessageScrollPane;
    private javax.swing.JTextArea MessageTextArea;
    private javax.swing.JLabel Welcome;
    // End of variables declaration//GEN-END:variables
}