/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;
import java.awt.Image;
import java.awt.geom.RoundRectangle2D;
import java.sql.*;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class ChangePassword extends javax.swing.JFrame {
    Connection connect = null;
    ResultSet result = null;
    PreparedStatement pst = null;
    String id, role;
    private boolean passVisible = false, temp = false;
    // Eye Icon
    ImageIcon eyeOpenIcon = new ImageIcon(getClass().getResource("/images/icons8-eye-16.png"));
    ImageIcon eyeClosedIcon = new ImageIcon(getClass().getResource("/images/icons8-hide-16.png"));
    
    public ChangePassword() {
        initComponents();
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 30, 30));
        // Database Connection
        connect = Database.getConnection();
        // Show Eye Icon
        Eye.setIcon(eyeClosedIcon);
        // Add Logo in Title Bar
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/edubridgeicon.png"));
            Image image = icon.getImage();
            this.setIconImage(image);
        } catch (Exception e) {
            System.err.println("Error loading icon: " + e.getMessage());
        }
    }
    
    public ChangePassword(String id, String role) {
        initComponents();
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 30, 30));
        this.id = id;
        this.role = role;
        // Database Connection
        connect = Database.getConnection();
        // Show Eye Icon
        Eye.setIcon(eyeClosedIcon);
        // Add Logo in Title Bar
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/edubridgeicon.png"));
            Image image = icon.getImage();
            this.setIconImage(image);
        } catch (Exception e) {
            System.err.println("Error loading icon: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChangePasswordPanel = new ui.GradientPanel();
        PasswordLabel = new javax.swing.JLabel();
        PasswordField = new RoundedPasswordField(20);
        ConfirmPasswordLabel = new javax.swing.JLabel();
        ConfirmPasswordField = new RoundedPasswordField(20);
        Eye = new javax.swing.JLabel();
        ChangeBtn = new RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        PasswordLabel.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        PasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PasswordLabel.setText("Password");

        PasswordField.setForeground(new java.awt.Color(153, 153, 153));
        PasswordField.setText("password");
        PasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFieldFocusLost(evt);
            }
        });

        ConfirmPasswordLabel.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        ConfirmPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ConfirmPasswordLabel.setText("Confirm Password");

        ConfirmPasswordField.setForeground(new java.awt.Color(153, 153, 153));
        ConfirmPasswordField.setText("password");
        ConfirmPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ConfirmPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ConfirmPasswordFieldFocusLost(evt);
            }
        });

        Eye.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Eye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EyeMouseClicked(evt);
            }
        });

        ChangeBtn.setBackground(new java.awt.Color(151, 137, 219));
        ChangeBtn.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        ChangeBtn.setText("Change");
        ChangeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ChangeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangeBtnMouseClicked(evt);
            }
        });
        ChangeBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ChangeBtnKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout ChangePasswordPanelLayout = new javax.swing.GroupLayout(ChangePasswordPanel);
        ChangePasswordPanel.setLayout(ChangePasswordPanelLayout);
        ChangePasswordPanelLayout.setHorizontalGroup(
            ChangePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangePasswordPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(ChangePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel)
                    .addGroup(ChangePasswordPanelLayout.createSequentialGroup()
                        .addComponent(ConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Eye))
                    .addComponent(ConfirmPasswordLabel))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChangePasswordPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ChangeBtn)
                .addGap(157, 157, 157))
        );
        ChangePasswordPanelLayout.setVerticalGroup(
            ChangePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangePasswordPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(PasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfirmPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ChangePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eye, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(ChangeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ChangePasswordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ChangePasswordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFieldFocusGained
        // TODO add your handling code here:
        if(PasswordField.getText().equals("password")){
            PasswordField.setText("");
            PasswordField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_PasswordFieldFocusGained

    private void PasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFieldFocusLost
        // TODO add your handling code here:
        if(PasswordField.getText().equals("")) {
            PasswordField.setText("password");
            PasswordField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_PasswordFieldFocusLost

    private void ConfirmPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConfirmPasswordFieldFocusGained
        // TODO add your handling code here:
        if(ConfirmPasswordField.getText().equals("password")){
            ConfirmPasswordField.setText("");
            ConfirmPasswordField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_ConfirmPasswordFieldFocusGained

    private void ConfirmPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConfirmPasswordFieldFocusLost
        // TODO add your handling code here:
        if(ConfirmPasswordField.getText().equals("")) {
            ConfirmPasswordField.setText("password");
            ConfirmPasswordField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_ConfirmPasswordFieldFocusLost

    private void EyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EyeMouseClicked
        // TODO add your handling code here:
        if(passVisible){
            PasswordField.setEchoChar('*');
            ConfirmPasswordField.setEchoChar('*');
            Eye.setIcon(eyeClosedIcon);
        } else {
            PasswordField.setEchoChar((char)0);
            ConfirmPasswordField.setEchoChar((char)0);
            Eye.setIcon(eyeOpenIcon);
        }
        passVisible = !passVisible;
    }//GEN-LAST:event_EyeMouseClicked

    private void ChangeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeBtnMouseClicked
        // TODO add your handling code here:
        String password = String.valueOf(PasswordField.getPassword());
        String confirmpassword = String.valueOf(ConfirmPasswordField.getPassword());
        
        if (password.equals("password") || password.isBlank()) {
            PasswordLabel.setForeground(Color.RED);
        } else {
            PasswordLabel.setForeground(Color.BLACK);
            temp = true;
        }
        if (confirmpassword.equals("password") || confirmpassword.isBlank()) {
            ConfirmPasswordLabel.setForeground(Color.RED);
        } else {
            ConfirmPasswordLabel.setForeground(Color.BLACK);
            temp = true;
        }
        if(temp ==true && !password.equals(confirmpassword)){
            PasswordLabel.setForeground(Color.RED);
            ConfirmPasswordLabel.setForeground(Color.RED);
            temp = false;
        } else if(temp == true){
            String query = "UPDATE `" + role + "` SET `ID`='"+id+"',`password`='"+confirmpassword+"' WHERE `ID`='"+id+"'";
            try {
                pst = connect.prepareStatement(query);
                pst.execute();

                DataUpdated dataupdated = new DataUpdated();
                dataupdated.setVisible(true);
                new Timer().schedule(new TimerTask() {
                    @Override
                    public void run() {
                        dataupdated.dispose();
                    }
                }, 1000);
                this.dispose();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex);
            }
        } else {
            Failed failed = new Failed();
            failed.setVisible(true);
            new Timer().schedule(new TimerTask() {
                @Override
                public void run() {
                    failed.dispose();
                }
            }, 1000);
        }
    }//GEN-LAST:event_ChangeBtnMouseClicked

    private void ChangeBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ChangeBtnKeyPressed
        // TODO add your handling code here:
        ChangeBtnMouseClicked(null);
    }//GEN-LAST:event_ChangeBtnKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeBtn;
    private javax.swing.JPanel ChangePasswordPanel;
    private javax.swing.JPasswordField ConfirmPasswordField;
    private javax.swing.JLabel ConfirmPasswordLabel;
    private javax.swing.JLabel Eye;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    // End of variables declaration//GEN-END:variables
}
