/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import java.sql.*;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class LogIn extends javax.swing.JFrame {
    Connection connect = null;
    ResultSet result = null;
    PreparedStatement pst = null;
    private boolean passVisible = false;
    // Eye Icon
    ImageIcon eyeOpenIcon = new ImageIcon(getClass().getResource("/images/icons8-eye-16.png"));
    ImageIcon eyeClosedIcon = new ImageIcon(getClass().getResource("/images/icons8-hide-16.png"));
    public LogIn() {
        initComponents();
        // Set Title
        this.setTitle("EduBridge University");
        // Database Connection
        connect = Database.getConnection();
        // Add Logo in Title Bar
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/edubridgeicon.png"));
            Image image = icon.getImage();
            this.setIconImage(image);
        } catch (Exception e) {
            System.err.println("Error loading icon: " + e.getMessage());
        }
        Eye.setIcon(eyeClosedIcon);
        new AttentionScreen().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainLoginPanel = new ui.GradientPanel();
        Logo = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        EmailField = new RoundedTextField(20);
        PasswordLabel = new javax.swing.JLabel();
        PasswordField = new RoundedPasswordField(20);
        Eye = new javax.swing.JLabel();
        LogInBtn = new RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainLoginPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/edubridgelogo.png"))); // NOI18N

        EmailLabel.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        EmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EmailLabel.setText("Email or UserName");

        EmailField.setForeground(new java.awt.Color(153, 153, 153));
        EmailField.setText("example@domain.com");
        EmailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailFieldFocusLost(evt);
            }
        });

        PasswordLabel.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        PasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PasswordLabel.setText("Password");

        PasswordField.setForeground(new java.awt.Color(153, 153, 153));
        PasswordField.setText("password");
        PasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFieldFocusLost(evt);
            }
        });

        Eye.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Eye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EyeMouseClicked(evt);
            }
        });

        LogInBtn.setBackground(new java.awt.Color(151, 137, 219));
        LogInBtn.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        LogInBtn.setText("LogIn");
        LogInBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogInBtnMouseClicked(evt);
            }
        });
        LogInBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LogInBtnKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout MainLoginPanelLayout = new javax.swing.GroupLayout(MainLoginPanel);
        MainLoginPanel.setLayout(MainLoginPanelLayout);
        MainLoginPanelLayout.setHorizontalGroup(
            MainLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainLoginPanelLayout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addGroup(MainLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainLoginPanelLayout.createSequentialGroup()
                        .addGroup(MainLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LogInBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Eye))
                    .addComponent(EmailLabel)
                    .addComponent(PasswordLabel)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        MainLoginPanelLayout.setVerticalGroup(
            MainLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLoginPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(Logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eye, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(LogInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 156, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainLoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EmailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFieldFocusGained
        // TODO add your handling code here:
        if(EmailField.getText().equals("example@domain.com")){
            EmailField.setText("");
            EmailField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_EmailFieldFocusGained

    private void EmailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFieldFocusLost
        // TODO add your handling code here:
        if(EmailField.getText().equals("")) {
            EmailField.setText("example@domain.com");
            EmailField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_EmailFieldFocusLost

    private void PasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFieldFocusGained
        // TODO add your handling code here:
        if(PasswordField.getText().equals("password")){
            PasswordField.setText("");
            PasswordField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_PasswordFieldFocusGained

    private void PasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFieldFocusLost
        // TODO add your handling code here:
        if(PasswordField.getText().equals("")) {
            PasswordField.setText("password");
            PasswordField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_PasswordFieldFocusLost

    private void EyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EyeMouseClicked
        // TODO add your handling code here:
        if(passVisible){
            PasswordField.setEchoChar('*');
            Eye.setIcon(eyeClosedIcon);
        } else {
            PasswordField.setEchoChar((char)0);
            Eye.setIcon(eyeOpenIcon);
        }
        passVisible = !passVisible;
    }//GEN-LAST:event_EyeMouseClicked

    private void LogInBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInBtnMouseClicked
        // TODO add your handling code here:
        String id = EmailField.getText();
        String password = String.valueOf(PasswordField.getPassword());
        
        if (id.equals("example@domain.com") && password.equals("password")){
            EmailLabel.setForeground(Color.RED);
            PasswordLabel.setForeground(Color.RED);
        } else if (id.equals("")) {
            EmailLabel.setForeground(Color.WHITE);
            PasswordLabel.setForeground(Color.RED);
        } else if (password.equals("")) {
            EmailLabel.setForeground(Color.RED);
            PasswordLabel.setForeground(Color.WHITE);
        } else {
            String adminQuery = "SELECT * FROM `admin` WHERE `email`= ? AND `password`= ?";
            String instructorQuery = "SELECT * FROM `instructor` WHERE `ID`=? AND `password`=?";
            String studentQuery = "SELECT * FROM `student` WHERE `ID`=? AND `password`=?";
            try {
                pst = connect.prepareStatement(adminQuery);
                pst.setString(1, id);
                pst.setString(2, password);
                
                result = pst.executeQuery();
                
                if (result.next()) {
                    LogInSuccessful loginsuccessful = new LogInSuccessful();
                    loginsuccessful.setVisible(true);
                    new Timer().schedule(new TimerTask() {
                        @Override
                        public void run() {
                            loginsuccessful.dispose();
                        }
                    }, 1000);
                    this.dispose();
                    new HomePageAdmin(id).setVisible(true);
                } else {
                    if(result != null) result.close();
                    if(pst != null) pst.close();
                    
                    pst = connect.prepareStatement(instructorQuery);
                    pst.setString(1, id);
                    pst.setString(2, password);

                    result = pst.executeQuery();
                    
                    if (result.next()) {
                        LogInSuccessful loginsuccessful = new LogInSuccessful();
                        loginsuccessful.setVisible(true);
                        new Timer().schedule(new TimerTask() {
                            @Override
                            public void run() {
                                loginsuccessful.dispose();
                            }
                        }, 1000);
                        this.dispose();
                        new HomePageInstructor(id).setVisible(true);
                    } else {
                        if(result != null) result.close();
                        if(pst != null) pst.close();

                        pst = connect.prepareStatement(studentQuery);
                        pst.setString(1, id);
                        pst.setString(2, password);

                        result = pst.executeQuery();

                        if (result.next()) {
                            LogInSuccessful loginsuccessful = new LogInSuccessful();
                            loginsuccessful.setVisible(true);
                            new Timer().schedule(new TimerTask() {
                                @Override
                                public void run() {
                                    loginsuccessful.dispose();
                                }
                            }, 1000);
                            this.dispose();
                            new HomePageAdmin(id).setVisible(true);
                        } else {
                            LogInFailed loginfailed = new LogInFailed();
                            loginfailed.setVisible(true);
                            new Timer().schedule(new TimerTask() {
                                @Override
                                public void run() {
                                    loginfailed.dispose();
                                }
                            }, 1000);
                            EmailField.setText("example@domain.com");
                            EmailField.setForeground(new Color(153,153,153));
                            PasswordField.setText("password");
                            PasswordField.setForeground(new Color(153,153,153));
                        }
                    }
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex);
            }
        }
    }//GEN-LAST:event_LogInBtnMouseClicked

    private void LogInBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LogInBtnKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            LogInBtnMouseClicked(null);
        }
    }//GEN-LAST:event_LogInBtnKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel Eye;
    private javax.swing.JButton LogInBtn;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel MainLoginPanel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    // End of variables declaration//GEN-END:variables
}
