/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;
import java.awt.Color;
import java.awt.Image;
import java.sql.*;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class SignIn extends javax.swing.JFrame {
    Connection connect = null;
    ResultSet result = null;
    PreparedStatement pst = null;
    public SignIn() {
        initComponents();
        // Set Title
        this.setTitle("EduBridge University");
        // Database Connection
        connect = Database.getConnection();
        // Add Logo in Title Bar
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/titlebarlogo.png"));
            Image image = icon.getImage();
            this.setIconImage(image);
        } catch (Exception e) {
            System.err.println("Error loading icon: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SigninMainPanel = new javax.swing.JPanel();
        LogInBtn = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        Password = new javax.swing.JLabel();
        UserNameField = new javax.swing.JTextField();
        Username = new javax.swing.JLabel();
        ToContinue = new javax.swing.JLabel();
        WelcomeBack = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        SigninMainPanel.setBackground(new java.awt.Color(66, 122, 118));
        SigninMainPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        SigninMainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogInBtn.setBackground(new java.awt.Color(205, 121, 62));
        LogInBtn.setFont(new java.awt.Font("Bodoni MT Black", 1, 14)); // NOI18N
        LogInBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogInBtn.setText("LogIn");
        LogInBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogInBtnMouseClicked(evt);
            }
        });
        SigninMainPanel.add(LogInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 340, 120, 40));

        PasswordField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PasswordField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        SigninMainPanel.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 400, 40));

        Password.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Username or Email:");
        SigninMainPanel.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 400, 40));

        UserNameField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        UserNameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        UserNameField.setToolTipText("");
        SigninMainPanel.add(UserNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 400, 40));

        Username.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Password:");
        SigninMainPanel.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 400, 40));

        ToContinue.setFont(new java.awt.Font("Bodoni MT Black", 1, 24)); // NOI18N
        ToContinue.setForeground(new java.awt.Color(255, 255, 255));
        ToContinue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ToContinue.setText("Sign in to Continue");
        SigninMainPanel.add(ToContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 58, 800, 50));

        WelcomeBack.setFont(new java.awt.Font("Bodoni MT Black", 1, 24)); // NOI18N
        WelcomeBack.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeBack.setText("Welcome Back!");
        SigninMainPanel.add(WelcomeBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 60));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/logo (2).png"))); // NOI18N
        Logo.setPreferredSize(new java.awt.Dimension(800, 600));
        SigninMainPanel.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SigninMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SigninMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogInBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInBtnMouseClicked
        // TODO add your handling code here:
        String email = UserNameField.getText();
        String password = String.valueOf(PasswordField.getPassword());
        
        if (email.equals("") && password.equals("")){
            Username.setForeground(Color.RED);
            Password.setForeground(Color.RED);
        } else if (email.equals("")) {
            Username.setForeground(Color.WHITE);
            Password.setForeground(Color.RED);
        } else if (password.equals("")) {
            Username.setForeground(Color.RED);
            Password.setForeground(Color.WHITE);
        } else {
            // Main Admin
            String query = "SELECT * FROM `admin` WHERE `email`=? AND `password`=?";
            try {
                pst = connect.prepareStatement(query);
                pst.setString(1, email);
                pst.setString(2, password);
                
                result = pst.executeQuery();
                
                if (result.next()) {
                    LogInSuccessful loginsuccessful = new LogInSuccessful();
                    loginsuccessful.setVisible(true);
                    new Timer().schedule(new TimerTask() {
                        public void run() {
                            loginsuccessful.dispose();
                            new HomePageAdmin(email).setVisible(true);
                        }
                    }, 1000);
                
                    this.dispose();
                } else {
                    LogInFailed loginfailed = new LogInFailed();
                    loginfailed.setVisible(true);
                    new Timer().schedule(new TimerTask() {
                        public void run() {
                            loginfailed.dispose();
                        }
                    }, 1000);
                    UserNameField.setText("");
                    PasswordField.setText("");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex);
            }
        }
    }//GEN-LAST:event_LogInBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogInBtn;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JPanel SigninMainPanel;
    private javax.swing.JLabel ToContinue;
    private javax.swing.JTextField UserNameField;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel WelcomeBack;
    // End of variables declaration//GEN-END:variables
}
