/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

/**
 *
 * @author DELL
 */
public class UserAlreadyExists extends javax.swing.JFrame {

    /**
     * Creates new form EmailAlreadyExists
     */
    public UserAlreadyExists() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserAlreadyExistsPanel = new javax.swing.JPanel();
        UserAlreadyExistsText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        UserAlreadyExistsPanel.setBackground(new java.awt.Color(151, 137, 219));
        UserAlreadyExistsPanel.setMinimumSize(new java.awt.Dimension(200, 100));
        UserAlreadyExistsPanel.setPreferredSize(new java.awt.Dimension(200, 100));

        UserAlreadyExistsText.setEditable(false);
        UserAlreadyExistsText.setBackground(new java.awt.Color(151, 137, 219));
        UserAlreadyExistsText.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        UserAlreadyExistsText.setForeground(new java.awt.Color(245, 245, 245));
        UserAlreadyExistsText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UserAlreadyExistsText.setText("User Already Exists");
        UserAlreadyExistsText.setBorder(null);
        UserAlreadyExistsText.setFocusable(false);

        javax.swing.GroupLayout UserAlreadyExistsPanelLayout = new javax.swing.GroupLayout(UserAlreadyExistsPanel);
        UserAlreadyExistsPanel.setLayout(UserAlreadyExistsPanelLayout);
        UserAlreadyExistsPanelLayout.setHorizontalGroup(
            UserAlreadyExistsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserAlreadyExistsPanelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(UserAlreadyExistsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        UserAlreadyExistsPanelLayout.setVerticalGroup(
            UserAlreadyExistsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserAlreadyExistsPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(UserAlreadyExistsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserAlreadyExistsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserAlreadyExistsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAlreadyExists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAlreadyExists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAlreadyExists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAlreadyExists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserAlreadyExists().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UserAlreadyExistsPanel;
    private javax.swing.JTextField UserAlreadyExistsText;
    // End of variables declaration//GEN-END:variables
}
